server:
  port: 8081

spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://localhost:${LOCAL_MYSQL_PORT}/health?serverTimezone=UTC
    username: ${LOCAL_MYSQL_USERNAME}
    password: ${LOCAL_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always

open-api:
  decoding-key: ${DECODING_KET}
  url: ${API_URL}

#초 단위
scheduled:
  initial-delay: 10
  fixed-rate: 604800 # 1주일

# 초 단위
rest-template:
  connect-timeout: 5
  read-timeout: 5



