debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.example: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://localhost:${LOCAL_MYSQL_PORT}/health?serverTimezone=UTC
    username: ${LOCAL_MYSQL_USERNAME}
    password: ${LOCAL_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true # 실제 데이터베이스와의 연결이 필요한 시점에서 초기화
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always


open-api:
  decoding-key: ${DECODING_KET}
  url: ${API_URL}

#초 단위
scheduled:
  initial-delay: 100
  fixed-rate: 604800 # 1주일



